<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260314230910 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE companies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, industry VARCHAR(255) NOT NULL, founded_year INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE employees (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, position VARCHAR(255) NOT NULL, photo VARCHAR(255) DEFAULT NULL, company_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BA82C300979B1AD6 ON employees (company_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BA82C300A76ED395 ON employees (user_id)');
        $this->addSql('CREATE TABLE projects (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, start_date DATE DEFAULT NULL, status VARCHAR(255) NOT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5C93B3A4979B1AD6 ON projects (company_id)');
        $this->addSql('CREATE TABLE employee_project (project_id INT NOT NULL, employee_id INT NOT NULL, PRIMARY KEY (project_id, employee_id))');
        $this->addSql('CREATE INDEX IDX_AFFF86E1166D1F9C ON employee_project (project_id)');
        $this->addSql('CREATE INDEX IDX_AFFF86E18C03F15C ON employee_project (employee_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(100) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('ALTER TABLE employees ADD CONSTRAINT FK_BA82C300979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE employees ADD CONSTRAINT FK_BA82C300A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A4979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE employee_project ADD CONSTRAINT FK_AFFF86E1166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_project ADD CONSTRAINT FK_AFFF86E18C03F15C FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE employees DROP CONSTRAINT FK_BA82C300979B1AD6');
        $this->addSql('ALTER TABLE employees DROP CONSTRAINT FK_BA82C300A76ED395');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A4979B1AD6');
        $this->addSql('ALTER TABLE employee_project DROP CONSTRAINT FK_AFFF86E1166D1F9C');
        $this->addSql('ALTER TABLE employee_project DROP CONSTRAINT FK_AFFF86E18C03F15C');
        $this->addSql('DROP TABLE companies');
        $this->addSql('DROP TABLE employees');
        $this->addSql('DROP TABLE projects');
        $this->addSql('DROP TABLE employee_project');
        $this->addSql('DROP TABLE users');
    }
}
